chaos_company_admin_add_category:
    path: /add
    defaults: { _controller: ChaosCompanyAdminBundle:Category:add }

chaos_company_admin_edit_category:
    path: /{id}/edit
    defaults: { _controller: ChaosCompanyAdminBundle:Post:edit }

chaos_company_admin_delete_category:
    path: /{id}/delete
    defaults: { _controller: ChaosCompanyAdminBundle:Post:delete }

chaos_company_admin_show_category:
    path: /{id}/show
    defaults: { _controller: ChaosCompanyAdminBundle:Post:show }

chaos_company_admin_list_category:
    path: /list
    defaults: { _controller: ChaosCompanyAdminBundle:Post:list }